fix: add missing format string argument
Compilation fails when using `-Werror=format-security` compiler flag:

```
elektroid.c: In function 'elektroid_ask_user_to_continue_show':
elektroid.c:205:42: error: format not a string literal and no format arguments [-Werror=format-security]
  205 |                                          GTK_BUTTONS_NONE, data->msg);
      |                                          ^~~~~~~~~~~~~~~~
```

The error is caused by a call to `gtk_message_dialog_new`, in which the format string argument is not a string literal and no format arguments follow.